#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#
#                                                                      #
#         Joomla playbook                                              #
#         Version:      01                                             #
#         Auther:      Babu Vijayanath                                 #
#                                                                      #
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#

---
- name: Install nrpe client
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: true
- name: set distro-specific variables
  include_vars: '{{ item }}'
  with_first_found:
        - '{{ ansible_os_family }}.yml'
        - default.yml

