---
- name: Import EPEL GPG key for CenOS 7
  rpm_key:
        key: http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
        state: present
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
- name: Import EPEL GPG key for CentOS 6
  rpm_key:
       key: http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-6
       state: present
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- name: Add YUM repo
  yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: http://dl.fedoraproject.org/pub/epel/$releasever/$basearch
      gpgcheck: yes
  when: ansible_distribution == 'CentOS' 
- name: Update the software package repository
  yum:
       name: '*'
       update_cache: yes
  when: ansible_distribution == 'CentOS' 
- name: Install NRPE client for CentOS
  yum: state=latest name={{ item }}
  with_items:
        - nrpe
        - nagios-plugins
  when: ansible_distribution == 'CentOS' 
- name: Edit NRPE configuration for CentOS
  lineinfile:
        path: /etc/nagios/nrpe.cfg
        regexp: '^allowed_hosts='
        line: 'allowed_hosts=127.0.0.1, 192.168.122.75'
  when: ansible_distribution == 'CentOS' 
- name: Start NRPE
  service:
        name: nrpe
        state: started
        enabled: true
- name: Add  rules in firewall for CentOS7/RHEL7
  command: firewall-cmd --add-port=5666/tcp --permanent
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
- name: Add  rules in iptables  for CentOS6/RHEL
  command: iptables  -A INPUT -m state --state NEW -m tcp -p tcp --dport 5666 -j ACCEPT
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- name: reload firewalld in CentOS7/RHEL7
  command: firewall-cmd --reload 
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7' 

- name: reload firewalld in CentOS6/RHEL6
  command: service iptables save
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'
